# Generated by Django 4.0 on 2021-12-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafehandsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='age',
            field=models.IntegerField(),
        ),
    ]
