# Generated by Django 4.0 on 2021-12-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafehandsApp', '0002_rename_child_report_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='child',
        ),
    ]
