# Generated by Django 4.0 on 2021-12-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafehandsApp', '0002_alter_babysitter_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='age',
            field=models.CharField(max_length=2),
        ),
    ]
